### ISSUE TITLE
Add a LandingPage with a list of playgrounds

### ISSUE THREAD

**Issue by AlexF090** [AlexF090/-playground-cologne#2]
## Value statement – a requirement, not a solution
As a **user** 
I need **a page where I can see a list of playgrounds** 

## Acceptance criteria (functional descriptions)
- [ ] A first list with some useful information of the API is available. 

## Tasks (to-dos for the team)
- [ ] Deal with the API, which data is available and which is NOT!
- [ ] Fetch data from API
- [ ] Create a component to create the list items for the playgrounds 
- [ ] The component should have only the most important data. (All other data will be displayed later in a detail page).
- [ ] Create a “LandingPage” with a map method
- [ ] Create a commit
- [ ] Create a PR

## Size
medium
